name: Bootstrap & Terraform Azure VM & Key Vault

on:
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure via OIDC
        uses: azure/login@v1
        with:
          auth-type: oidc
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bootstrap backend resources
        run: |
          az group create \
            --name rg-tfstate \
            --location eastus
          az storage account create \
            --name tfstate2tuff \
            --resource-group rg-tfstate \
            --sku Standard_LRS \
            --kind StorageV2 \
            --https-only true \
            --only-show-errors || echo "Storage exists, skipping"
          az storage container create \
            --name tfstate \
            --account-name tfstate2tuff \
            --only-show-errors || echo "Container exists, skipping"

      - name: Export Azure environment variables
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}"         >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}"        >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Write backend config
        run: |
          cat <<EOF > backend.tf
          terraform {
            backend "azurerm" {
              resource_group_name   = "rg-tfstate"
              storage_account_name  = "tfstate2tuff"
              container_name        = "tfstate"
              key                   = "prod/terraform.tfstate"
            }
          }
          EOF

      - name: Write terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          ssh_public_key = <<KEY
          ${{ secrets.SSH_PUBLIC_KEY }}
          KEY
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
