name: Cert Download to VM

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  download-cert:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC:        "true"
      ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: cert-download

      - name: Terraform Plan
        run: terraform plan \
              -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
              -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
              -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
              -var="vm_id=${{ vars.vm_id }}"
        working-directory: cert-download

      - name: Terraform Apply
        run: terraform apply -auto-approve \
              -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
              -var="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
              -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
              -var="vm_id=${{ vars.vm_id }}"
        working-directory: cert-download
